Primeira alteração
kyriosdata/integracao pull request #43
Opened 2020-09-16 15:35 UTC by josimarMorais

Feita a primeira alteração para avaliação do professor

2020-09-16 22:18 UTC, kyriosdata commented on onepage/organizacionais.md
>  Coloque aqui o "resumo" de uma página, no máximo 4 parágrafos,
Você pode remover o primeiro parágrafo, ou esta primeira sentença "Coloque aqui ...".

2020-09-22 13:27 UTC, josimarMorais commented on onepage/organizacionais.md
>  Coloque aqui o "resumo" de uma página, no máximo 4 parágrafos,
Foi realizado a retirada do primeiro parágrafo, conforme sugerido pelo professor.

2020-09-23 14:44 UTC, kyriosdata commented on onepage/organizacionais.md
> +Os processos organizacionais são os processos concebidos para fornecer os recursos necessários para que o projeto/serviço atenda às expectativas e necessidades das partes interessadas da organização.
A definição é do MPS.BR, ou seja, é aconselhável citar a referência em questão.

2020-09-23 14:45 UTC, kyriosdata commented on onepage/organizacionais.md
> +Esses processos são divididos em Gerência de configuração, Aquisição, Medição, Gerência de Decisões, Gerência de Recursos Humanos, Gerência de Processos e Gerência Organizacional:
Melhor seria: "Os processos organizacionais incluem os processos..."

2020-09-23 14:46 UTC, kyriosdata commented on onepage/organizacionais.md
> +- Na Gerência de configuração o propósito é estabelecer e manter a integridade de produtos de trabalho e disponibilizá-los a todos os envolvidos.
Gerência de configuração não é um processo organizacional.

2020-09-23 14:47 UTC, kyriosdata commented on onepage/organizacionais.md
> +- Na Aquisição o propósito é gerenciar a aquisição de produtos que satisfaçam às necessidades expressas pelo adquirente.
Melhor seria "O processo..."  em vez de "No..." ou "Na..."

2020-09-23 14:48 UTC, kyriosdata requested changes
Veja as observações. Vamos pensar em como organizar tais processos em uma única página!

2020-09-23 22:44 UTC, josimarMorais commented on onepage/organizacionais.md
> +Os processos organizacionais são os processos concebidos para fornecer os recursos necessários para que o projeto/serviço atenda às expectativas e necessidades das partes interessadas da organização.
Foi colocado a referência do MPS.BR

2020-09-23 22:51 UTC, josimarMorais commented on onepage/organizacionais.md
> +Esses processos são divididos em Gerência de configuração, Aquisição, Medição, Gerência de Decisões, Gerência de Recursos Humanos, Gerência de Processos e Gerência Organizacional:
foi mudado

2020-09-23 22:52 UTC, josimarMorais commented on onepage/organizacionais.md
> +- Na Aquisição o propósito é gerenciar a aquisição de produtos que satisfaçam às necessidades expressas pelo adquirente.
Mudança realizada

2020-09-23 22:56 UTC, josimarMorais commented on onepage/organizacionais.md
> +- Na Gerência de configuração o propósito é estabelecer e manter a integridade de produtos de trabalho e disponibilizá-los a todos os envolvidos.
por uma divergência de documentos ouve essa divergência de informação. Já resolvido

2020-10-07 13:55 UTC, kyriosdata commented
COM APROVEITAMENTO. :+1:

2020-10-07 13:55 UTC, merged