Teste inicial em aula
kyriosdata/integracao pull request #45
Opened 2020-09-16 22:36 UTC by Murilo001

Pull request em aula para testes.

2020-09-16 22:40 UTC, kyriosdata commented
A página deve conter exclusivamente informações sobre "Construção de Software". Não há espaço para outras informações.

2020-09-23 14:42 UTC, kyriosdata requested changes
Murilo, é preciso realizar a atividade para o cômputo de nota. Você tem presença pelo realizado, mas observe que não há nada pertinente à construção. Como posso ser ajudar?

2020-10-06 02:46 UTC, Murilo001 commented
Boa noite Professor, estive sobrecarregado de atividades nos últimos dias e acabei me desleixando quanto aos commits, enviei agora o resumo, seria possível aceitar a resolução de tópicos anteriores com um valor menor na nota? Ajudaria bastante. 

Agradeço desde já.

2020-10-07 13:53 UTC, kyriosdata commented
Olá Murilo, vamos nos esforçar para manter os prazos. Lembro que as atividades recebem COM ou SEM aproveitamento. São apenas dois valores. 

Para esta o resultado é

COM APROVEITAMENTO. :+1:

2020-10-07 13:54 UTC, merged